spring.datasource.url=jdbc:postgresql://localhost:5432/spring_security_practice
spring.datasource.username=postgres
spring.datasource.password=Ruhul@2002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=vCcrHuEAjobyUXtyaQVNvVbpFJkvAdln32Ju5fmMXUY=
jwt.issuer =spring-security-practice
jwt.expiry=900